# Copyright 2022 @BukanDev
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# https://github.com/BukanDev/spill-and-drink
# limitations under the License.

import os
from pyrogram import Client, filters
from pyrogram.types import Message

from random import choice
from dotenv import load_dotenv

load_dotenv(".env")

BOT_TOKEN = os.environ.get("BOT_TOKEN")
API_ID = int(os.environ.get("API_ID"))
API_HASH = os.environ.get("API_HASH")
CHANNEL = os.environ.get("CHANNEL")
OWNER = os.environ.get("OWNER")
LOG_CHAT = os.environ.get("LOG_CHAT")

bot = Client("kontolbot",
            api_id=API_ID,
            api_hash=API_HASH,
            bot_token=BOT_TOKEN)
            
print("Bot sudah siap di gunakan")

# bucin text
BUCIN = [
  "Orang bilang jadi penyair itu susah Nggak Mereka belum jatuh cinta aja",
  "Kalau misal aku lahir seribu tahun yang lalu, aku pasti akan tetap menunggumu",
  "Kamu tau gak, kenapa kalo belajar menghafal aku selalu melihat ke atas? Soalnya kalo merem langsung kebayang wajah kamu",
  "Aneh rasanya bagaimana dengan hanya mendengar namamu saja, hatiku bisa tersayat teriris ngilu seperti luka basah yang tersiram cuka?",
  "Kalau jadi ksatria itu gampang Yang susah itu jadi pahlawan hati kamu",
  "Kalau pahlawan punya baju besi, aku nggak Soalnya aku rela tertusuk cinta kamu",
  "Ketika kamu telah membuatnya bahagia dan dia masih memilih orang lain, yakinlah Mungkin kamu belum kaya!",
  "Kamu seperti pensil warna deh, bisa mewarnai hari-hariku",
  "Kalo kamu bidadari, akan kupatahkan semua sayapmu karena aku gak rela kamu kembali ke surga",
  "Pahlawan itu kan mereka yang berjuang buat negara, berarti aku juga pahlawan dong, soalnya merjuangin masa depan kita",
  "Kamu itu kayak pahlawan ya, hebat meruntuhkan pertahanan hatiku",
  "Kalau pahlawan dikenang, kamu nggak bakalan jadi kenangan",
  "Makan apa pun aku suka asal sama kamu, termasuk makan ati",
  "Kalau kamu jadi senar gitar, aku nggak mau jadi gitaris Aku nggak mau ada risiko mutusin kamu",
  "Aku itu kayak kipas angin Meski tengok kanan tengok kiri, tetap ada di tempat yang sama Tetep sama kamu, tetep mencintai kamu",
  "Kalau aku jadi wakil rakyat, pasti aku gagal Soalnya aku selalu mikirin kamu, bukan rakyat",
  "Kalau aku jadi gubernur, aku pasti langsung dimarahi rakyat Soalnya, aku nggak bisa ngomong lancar kalau kamu nggak di sampingku",
  "Aku adalah murid teladan karena setiap hari aku selalu belajar, belajar mencintaimu sepenuh hati",
  "Lihat kebunku, penuh dengan bunga Lihat matamu, hatiku berbunga-bunga",
  "Beda operator nggak apa-apa deh, asal nanti nama kamu sama aku di Kartu Keluarga yang sama",
  "Aku rela menunggu, meski kamu tak memberiku kabar, bahkan aku sadar jika ingin kamu tinggalkan",
  "Aku tidak bisa berjanji untuk menjadi yang baik, tapi aku berjanji akan selalu mendampingi kamu",
  "Sampai detik ini kamu masih menjadi alasan kenapa hatiku belum mau menerima siapapun",
  "Jika aku bisa menjadi segalanya, aku ingin menjadi air mata kamu Lalu aku bisa lahir di matamu, hidup di pipimu, dan mati di bibirmu",
  "Kalau aku jadi wakil rakyat aku pasti gagal, gimana mau mikirin rakyat kalau yang selalu ada dipikiran aku hanyalah dirimu",
  "Entah mengapa tiap melihat kamu, aku keingat akan ujian Susah sih, tetapi tetap saja harus diperjuangkan demi mendapatkanmu",
  "Semua orang bisa bilang cinta, akan tetapi tak semua orang bisa setia",
  "Aku mencintaimu lebih dari arti kata-kata, mengungkapkan perasaan, dan memikirkan pikiran",
  "Cinta aku tuh kaya kamera, kalau udah fokus ke satu orang yang lain pasti ngeblur",
  "Aku lebih suka apel daripada anggur, soalnya aku lebih suka ngapelin kamu daripada nganggurin kamu",
  "Hidup tidak selalu mudah, tapi jauh lebih mudah dengan kamu di sisiku",
  "Hanya dengan hitungan jam kita akan bertemu lagi, tapi rasanya sangat lama bagaikan satu dekade Tak terbayang seberapa girangnya hati ini berada dalam pelukanmu",
  "Saat aku sedang bersamamu rasanya 1 jam hanya 1 detik, tetapi jika aku jauh darimu rasanya 1 hari menjadi 1 tahun",
  "Kolak pisang tahu sumedang, walau jarak membentang cintaku takkan pernah hilang",
  "Aku ingin menjadi satu-satunya, bukan salah satunya",
  "Lihat kebunku, penuh dengan bunga Lihat matamu, hatiku berbunga-bunga",
  "Berjanjilah untuk terus bersamaku sekarang, esok, dan selamanya",
  "Semenjak aku berhenti berharap pada dirimu, aku jadi tidak semangat dalam segala hal",
  "Mungkin kebahagiaan bersamamu hanya seperti mimpi, tapi biarlah mimpi itu terus menemani di setiap tidurku",
  "Semakin aku tahu bagaimana sikapmu, semakin aku lelah untuk mempertahankan hubungan ini",
  "Rindu tidak hanya muncul karena jarak yang terpisah, tapi juga karena keinginan yang tidak terwujud",
  "Kamu tidak akan pernah jauh dariku, kemanapun aku pergi kamu selalu ada, karena kamu selalu di hatiku, yang jauh hanya raga kita bukan hati kita",
  "Aku tahu dalam setiap tatapanku, kita terhalang oleh jarak dan waktu, tapi aku yakin kalau nanti kita pasti bisa bersatu",
  "Merindukanmu tanpa pernah bertemu sama halnya dengan menciptakan lagu yang tak pernah ternyayikan",
  "Ada kalanya jarak selalu menjadi penghalang antara aku sama kamu, tapi tetap saja di hatiku kita selalu dekat",
  "Jika hati ini tak mampu membendung segala kerinduan, apa daya tak ada yang bisa aku lakukan selain mendoakanmu",
  "Mungkin di saat ini aku hanya bisa menahan kerinduan ini Sampai tiba saatnya nanti aku bisa bertemu dan melepaskan kerinduan ini bersamamu",
  "Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu",
  "Dalam dinginnya malam, tak kuingat lagi; Berapa sering aku memikirkanmu juga merindukanmu",
  "Merindukanmu itu seperti hujan yang datang tiba-tiba dan bertahan lama Dan bahkan setelah hujan reda, rinduku masih terasa",
  "Kalau jelangkungnya kaya kamu, dateng aku jemput, pulang aku anter, deh",
  "Makan apapun aku suka asal sama kamu, termasuk makan hati",
  "Cinta itu kaya hukuman mati Kalau nggak ditembak, ya digantung",
  "Mencintaimu itu kayak narkoba: sekali coba jadi candu, gak dicoba bikin penasaran, ditinggalin bikin sakau",
  "Gue paling suka ngemil karena ngemil itu enak Apalagi ngemilikin kamu sepenuhnya",
  "Dunia ini cuma milik kita berdua Yang lainnya cuma ngontrak",
  "Bagi aku, semua hari itu adalah hari Selasa Selasa di Surga bila dekat denganmu",
  "Bagaimana kalau kita berdua jadi komplotan penjahat? Aku curi hatimu dan kamu curi hatiku",
  "Kamu itu seperti kopi yang aku seruput pagi ini Pahit, tapi bikin nagih",
  "Aku sering cemburu sama lipstikmu Dia bisa nyium kamu tiap hari, dari pagi sampai malam",
  "Di jiwa yang santuy terdapat jiwa kebucinan yang mendarah daging Kwkwk",
  "Bingung pengen marah-marah Tapi bingung pengen marah ke siapa? Terkadang diam memang jalan terbaik buat masyarakat santuy",
  "Awalnya sih diperlakukan dengan istimewa Tapi akhir-akhirnya meninggalkan rasa kecewa sadd bngst 🙁",
  "Gak butuh orang yang sayangnya cuma sementara",
  "Pengen punya temen yang bisa di tabokin",
  "Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu",
  "Hanya mendengar namamu saja sudah bisa membuatku tersenyum seperti orang bodoh",
  "Aku tau teman wanitamu bukan hanya satu dan menyukaimu pun bukan hanya aku",
  "Semenjak aku berhenti berharap pada dirimu, aku jadi tidak semangat dalam segala hal",
  "Terkadang aku iri sama layangan Talinya putus saja masih dikejar kejar dan gak rela direbut orang lain",
  "Aku tidak tahu apa itu cinta, sampai akhirnya aku bertemu denganmu Namun, saat itu juga aku tahu rasanya patah hati",
  "Mengejar itu capek, tapi lebih capek lagi menunggu Menunggu kamu menyadari keberadaanku",
  "Denganmu, jatuh cinta adalah patah hati paling sengaja",
  "Sangat sulit merasakan kebahagiaan hidup tanpa kehadiran kamu disisiku",
  "Sendainya kamu tahu, sampai saat ini aku masih mencintaimu",
  "Kamu sudah menjadi bagian dari rencana masa depanku, kamu pergi, aku takut masa depanku tak lagi sempurna tanpamu",
  "Ketika Tuhan memberikan satu kebahagiaan untukku, maka aku memilih memberikan kebahagiaan itu untukmu",
  "Cinta tapi tak dianggap itu seperti sakit tapi tak berdarah",
  "Aku tidak tahu apakah tempatku benar-benar di sini Aku tidak punya seorangpun untuk diajak bicara",
  "Kamu benar-benar mencintai seseorang ketika kamu tidak bisa membencinya meskipun ia telah menyakitimu",
  "Tidak peduli seberapa ingin kamu kembali ke masa lalu, di sana tetap tidak akan ada hal baru yang bisa kamu lihat",
  "Aku mencintaimu dengan segenap hatiku, tapi kau malah membagi perasaanmu dengan orang lain",
  "Aku bingung, apakah aku harus kecewa atu tidak? Jika aku kecewa, emang siapa diriku baginya? Kalau aku tidak kecewa, tapi aku menunggu ucapannya",
  "Melihatmu bahagia adalah kebahagiaanku, walaupun bahagiamu tanpa bersamaku",
  "Rinduku seperti ranting yang tetap berdiriMeski tak satupun lagi dedaunan yang menemani, sampai akhirnya mengering, patah, dan mati",
  "Kurasa kita sekarang hanya dua orang asing yang memiliki kenangan yang sama",
  "Buatlah aku bisa membencimu walau hanya beberapa menit agar tidak terlalu berat untuk melupakanmu",
  "Aku terkadang iri dengan sebuah benda Tidak memiliki rasa namun selalu dibutuhkan Berbeda dengan aku yang memiliki rasa, namun ditinggalkan dan diabaikan",
  "Demi cinta kita menipu diri sendiri Berusaha kuat nyatanya jatuh secara tak terhormat",
  "Mencintaimu mungkin menghancurkanku, tapi entah bagaimana meninggalkanmu tidak memperbaikiku",
  "Kamu adalah yang utama dan pertama dalam hidupku, tapi aku adalah yang kedua bagimu",
  "Jangan berhenti mencinta hanya karena pernah terluka Karena tak ada pelangi tanpa hujan, tak ada cinta sejati tanpa tangisan",
  "Aku punya sejuta alasan untuk melupakanmu, tapi tak ada yang bisa memaksaku untuk berhenti mencintaimu",
  "Terkadang seseorang terasa sangat bodoh hanya untuk mencintai seseorang",
  "Bukannya tak pantas ditunggu, hanya saja sering memberi harapan palsu",
  "Sebagian diriku merasa sakit, mengingat dirinya yang sangat dekat, tapi tak tersentuh",
  "Hal yang terbaik dalam mencintai seseorang adalah dengan diam-diam mendoakannya",
  "Kuharap aku bisa menghilangkan perasaan ini secepat aku kehilanganmu",
  "Anggaplah aku rumahmu, jika kamu pergi kamu mengerti kemana arah pulang Menetaplah bila kamu mau dan pergilah jika kamu bosan",
  "Kamu adalah patah hati terbaik yang gak pernah aku sesali",
  "Jika mencintaimu itu seperti bersekolah, tanggal merah pun aku akan hadir Karena mencintaimu tak ada kata libur bagiku",
  "Balon kalau diisi angin semakin lama semakin ringan Hatiku kalau diisi kamu semakin lama semakin ingin ke pelaminan",
  "Menahan lapar aku bisa, menahan rindu padamu aku tak mampu",
  "Cintaku ke kamu tuh kayak utang, awalnya kecil, didiemin, tau-tau gede sendiri",
  "Kamu punya spidol item ga? Buat apa? Mau warnain kalender, biar ga ada kata libur dalam mencintaimu",
  "Kalau aku jadi wakil rakyat aku pasti gagal deh Gimana mau mikirin rakyat, kalau yang selalu ada di pikiranku hanyalah kamu",
  "Aku sukanya sih apel dibandingkan anggur, makanya aku suka ngapelin kamu ketimbang nganggurin kamu",
  "Saat di sampingmu, aku seperti mentega di atas wajan panas Langsung meleleh",
  "Daripada aku daftar jadi boyband, mending aku daftar jadi boyfriend kamu aja dech",
  "Untung rinduku padamu itu tidak bayar Kalau bayar, aku sudah jadi gembel",
  "Kamu duduk di sampingku dan kurasa aku lupa bagaimana bernafas",
  "Sungguh menakjubkan bagaimana satu percakapan kecil dapat mengubah segalanya selamanya",
  "Kamu harus membiarkan aku mencintaimu, biarkan aku menjadi orang yang memberimu semua yang kamu inginkan dan butuhkan",
  "Aku membutuhkanmu karena kamu membuatku tersenyum bahkan ketika kamu tidak di sisiku",
  "Aku mengagumi pikiranmu Aku jatuh cinta pada kepribadianmu Penampilanmu hanya bonus",
  "Mencintaimu dan dicintai olehmu adalah hadiah paling berharga yang pernah aku terima",
  "Aku tidak ingin menjadi favoritmu atau yang terbaik untukmu Aku ingin menjadi satu-satunya dalam hatimu dan melupakan sisanya",
  "Sulit bagiku untuk berpura-pura bahwa aku tidak menyukaimu padahal pada kenyataannya aku tergila-gila padamu",
  "Ketika aku memikirkanmu, aku akhirnya memiliki seringai bodoh di wajahku",
  "Biarkan aku membuatmu bahagia selamanya Kamu hanya perlu melakukan satu hal: jatuh cinta denganku",
  "Kolak pisang tahu Sumedang, walau jarak membentang cintaku takkan hilang",
  "Bagiku, semua hari itu Selasa Selasa indah bila di dekatmu",
  "Aku tanpamu bagaikan ambulans tanpa wiuw wiuw wiuw",
  "Sayang, kita putus saja, ya? Kita sudah nggak cocok buat pacaran, kita cocoknya itu menikah",
  "Kamu sebaiknya selalu pakai wifi agar hati kita selalu terkoneksi",
  "Ngemil apa yang paling enak? Ngemilikin kamu sepenuhnya",
  "Kamu adalah alasanku tetap bertahan di tanggal tua",
  "Aku rela dibilang bucin, yang penting kamu nggak ngilang",
  "Saat bertemu denganmu, jantung hatiku terasa berhenti berdetak Tapi, kenapa nggak mati-mati, ya?",
  "Aku nggak rela kalau kamu demam, tapi aku rela kalau aku demam rindu sama kamu",
  "Nggak apa-apa kok kamu gendutan, hatiku masih muat tuh buat kamu",
  "Beda operator nggak apa-apa deh, asal nanti nama kamu sama aku di Kartu Keluarga yang sama",
  "Laut kan kusebrangi, gunung pun akan kudaki hanya untukmu",
  "Tatapanmu memanglah sederhana, namun dapat mengalihkan dunia",
  "Aku nggak suka kalau kehujanan, tapi aku selalu suka kalau kehujanan cinta kamu",
  "Kamu tahu nggak, aku seperti mentega, kamu seperti wajan panas Soalnya aku meleleh tiap lihat kamu",
  "Kalau aku jadi wakil rakyat, pasti aku gagal Soalnya aku selalu mikirin kamu, bukan rakyat",
  "Aku divonis menjadi terdakwa karena telah mengambil hatimu Dan hukumannya mencintaimu seumur hidupku",
  "Lampu itu pasti cemburu sama kamu, soalnya mata kamu terang banget buat menerangi masa depanku",
  "Kalau pahlawan punya baju besi, aku nggak Soalnya aku rela tertusuk cinta kamu",
  "Lihat kebunku, penuh dengan bunga Lihat matamu, hatiku berbunga-bunga",
  "Jika rindu ibarat uang, mungkin aku sudah menjadi orang terkaya di dunia karena telah menanggung rindu padamu",
  "Kamu itu kayak pahlawan ya, hebat meruntuhkan pertahanan hatiku",
  "Kalau aku jadi gubernur, aku pasti langsung dimarahi rakyat Soalnya, aku nggak bisa ngomong lancar kalau kamu nggak di sampingku",
  "Tiap kali kamu senyum, seluruh dunia juga sedang tersenyum",
  "Tatapanmu memanglah sederhana, namun dapat mengalihkan dunia",
  "Berjanjilah untuk terus bersamaku sekarang, esok, dan selamanya",
  "Bila mencintaimu adalah ilusi, maka izinkan aku berimajinasi selamanya",
  "Aku nggak percaya sama pandangan pertama Aku percayanya sama takdir kalau kamu bakalan jadi jodohku",
  "Aku nggak rela kalau harus jadi penikmat senja, aku maunya jadi penikmat senyummu",
  "Kamu tahu kalau sungai Danube itu terpanjang di Eropa? Sepanjang itulah cintaku sama kamu",
  "Mata kamu itu sama persis energinya sama matahari kalau digabungin sama bulan Nggak tertandingi",
  "Jika kamu adalah bunga, maka aku adalah sang lebah yang senantiasa membuatmu indah",
  "Di bumi, gerak jatuh namanya gravitasi, di hati namanya cinta selalu bersemi",
  "Aku mencintaimu seperti anak kecil yang suka es krim",
  "Cinta laksana pembodohan Hanya karena namamu saja sudah membuatku gila",
  "Aku memang pendiam, diam-diam jatuh cinta sama kamu",
  "Aku selalu mendung tiap kali kamu pergi jauh",
  "Aku tak butuh hartamu, yang aku butuhkan hanyalah senyum bahagia dan canda tawamu saja",
  "Ketemu sama kamu itu kayak mau melihat meteor Susah, tapi indah",
  "Aku bersedia menjadi badutmu setiap hari dengan bertingkah lucu untuk membuatmu selalu tertawa dan melupakan air mata",
  "Kamu itu kayak kopi Bukan pahit, tapi candu",
  "Kamu itu kayak pelangi, ya Ada sehabis mendung di hatiku",
  "Cintaku seperti jam pasir Semakin hati kian terpenuhi, maka otak akan kian tak terisi",
  "Kalau kamu jadi senar gitar, aku nggak mau jadi gitaris Aku nggak mau ada risiko mutusin kamu",
  "Jangan rindu, berat, kamu nggak akan kuat Biar aku saja yang merindukanmu",
  "Kalau sabar adalah barang yang diperjualbelikan, maka penantianku akan kehadiran dirimu ini sudah membuatku menjadi gelandangan",
  "Hujan pergi ninggalin pelangi, kalau kamu pergi ninggalin air mataku",
  "Tuku lilin, entuk bonus fanta Meskipun kowe nyebelin, nanging aku tetap cinta(Beli lilin, dapat bonus fanta Msekipun kamu nyebelin, aku tetap cinta)",
  "Ora penting mikir malam mingguan, seng penting malam lamaran(Nggak penting mikir malam minggu, yang penting malam lamaran)",
  "Kacang iku gurih, tapi nek dikacangin iku perih(Kacang itu gurih, tapi kalau dikacangin itu perih)",
  "Saat dewe podo–podo adoh, siji sing kudu koe ngerti, bakal tak jogo tresno iki sampe matek(Saat jarak memisahkan kita, satu hal yang harus kamu tahu, aku akan menjaga cinta ini sampai mati)",
  "Sing wis lunga lalekno, sing durung teko entenono, sing wis ono syukurono(Yang sudah pergi lupakanlah, yang belum datang tunggulah, dan yang sudah ada syukurilah)",
  "Koe kuwi koyo bintang, sing indah didelok tapi susah untuk digapai”(Kamu itu seperti bintang, yang indah dilihat tapi susah untuk digapai)",
  "Wajahmu jan koyo wong susah Iyo, susah dilalekne(Wajahmu seperti orang susah Iya, susah untuk dilupakan)",
  "Akeh manungsa ngrasakaken tresna, tapi lalai lan ora kenal opo kui hakekate atresna(Banyak manusia merasakan cinta, namun mereka lupa tidak mengenal hakikat cinta sebenarnya)",
  "Mergo seng gaene ngekek’i cokelat bakal kalah karo seng ngewehi seperangkat alat sholat karo nyanyi lagu akad(Karena yang sering memberi cokelat akan kalah dengan yang memberi seperangkat alat solat dan nyanyi lagu akad)",
  "Rasa nyaman sing sempurna yo iku lek kowe gelem meluk aku(Rasa nyaman yang sempurna ya itu kalau kamu mau meluk aku)",
  "Iso ae aku ngelalikne koe tapi kenangane kui seng susah dilaleke(Bisa saja aku melupakan kamu tapi kenangannya itu yang susah dilupakan)",
  "Uwong duwe pacar iku kudu sabar ambek pasangane Opo meneh sing gak duwe(Orang yang punya pacar itu haruslah bersabar dengan pasangan yang dimilikinya Apalagi yang gak punya)",
  "Aku ra njaluk luweh, aku nggur njalok ojo lungo nek ati(Aku nggak minta banyak, aku hanya minta jangan pergi dari hati)",
  "Jelas aku butuh atimu, butuh awakmu, butuh perhatianmu, ora butuh duwitmu(Jelas aku butuh hatimu, butuh kamu, butuh perhatianmu, tidak butuh uangmu)",
  "Aku ora butuh GPS, nek karo kowe aku wis yakin kudu ning ngendi(Aku tidak butuh GPS, kalau sama kamu, aku sudah yakin mau ke mana)",
  "Kawula mung saderma, mobah-mosik kersaning hyang sukmo(Lakukan yang kita bisa, setelahnya serahkan kepada Tuhan)",
  "Dalan lurus akeh jeglongan, menggok sithik nemu tikungan Yen wis cinta kudu bertahan, ben gak ngrasakke kelangan(Jalan lurus banyak berlubang, belok sedikit ada tikungan Kalau sudah cinta harus bertahan, agar tak merasakan kehilangan)",
  "Konco dadi cinta Sampek kegowo turu, ngimpi ngusap pipimu Tansah nyoto keroso konco dadi tresno(Teman jadi cinta sampai terbawa tidur, mimpi mengusap pipimu Seperti kenyataan terasa seperti teman jadi cinta)",
  "Gusti iku cedhak tanpa senggolan, adoh tanpa wangenan(Tuhan itu dekat meski tubuh kita tidak dapat menyentuhnya, jauh tiada batasan)",
  "Aku pancen lelah, tapi aku janji ora bakal nyerah nggo nyanding sliramu(Aku memang lelah, tapi aku janji tidak akan menyerah untuk bersanding denganmu)",
  "Move on kuwi dudu berusaha nglalekke ya, tapi ngikhlaske lan berusaha ngentukke sing luwih apik luwih seko sing mbiyen-mbiyen(Move on itu bukan berusaha melupakan ya, tapi mengikhlaskan dan berusaha mendapatkan yang lebih baik dari sebelum-sebelumnya)",
  "Natas, nitis, netes(Dari Tuhan kita ada, bersama Tuhan kita hidup, dan bersatu dengan Tuhan kita kembali)",
  "Cintaku nang awakmu iku koyok kamera, fokus nang awakmu tok liyane ngeblur(Cintaku padamu seperti kamera, fokus pada dirimu, yang lain ngeblur)",
  "Aku duduk cah romantis sing iso berkata kata manis, nanging aku mung bocah humoris sing iso berkata manis(Aku bukan anak romantis yang bisa berkata manis, tapi aku anak humoris yang bisa berkata manis)",
  "Kowe gelem ngajari aku ora? Ngajari ben pantes nggo kowe(Kamu mau tidak mengajari aku? Ajari aku agar pantas untukmu)",
  "Witing tresno jalaran seko sering dijak dolan rono-rono(Cinta tumbuh dari sering diajak jalan ke sana kemari)",
  "Ojo lungo, aku jek tresno(Jangan pergi, aku masih cinta)",
  "Nyenderlah neng pundak ku, Sampek koe ngrasak ke nyaman, Mergo wes kudune koyo ngunu aku nggawe nyaman atimu(Bersandarlah di pundakku sampai kau merasakan nyaman, karena sudah seharusnnya aku memang aku membuatmu nyaman)",
  "Rino wengi aku tansah kelingan sliramu(Siang malam aku selalu teringat dirimu)",
  "Seng paling tak wedeni orep neng dunio udu kelangan koe, tapi wedi nek koe kelangan kebahagiaan ne sampean(Yang paling ku takutkan dalam dunia ini bukanlah kehilanganmu, tapi aku takut kamu kehilangan kebahagiaanmu)",
  "Mak deg, mak tratap Makmu makku besanan(Bikin deg-degan, bikin tratapan Ibumu, ibuku jadi besan)",
  "Kerjo tak lakoni, duwet tak tabungi, insyaallah tahun ngarep, sholatmu tak imami(Kerja aku lakukan, uang aku tabung, Insya Allah tahun depan, salatmu aku imami)",
  "Aku tanpamu bagaikan sego kucing ilang karete Ambyar(Aku tanpamu bagai nasi kucing hilang karetnya, hancur)",
  "Gusti yen arek iku jodohku tulung dicidakaken, yen mboten joduhku tulung dijodohaken(Tuhan jika dia adalah jodohku tolong didekatkan, dan jika bukan tolong dijodohkan)",
  "Kaosku suwek kecantol lawang Gayane cuek, asline sayang(Kaosku robek tergores pintu Bergaya cuek, aslinya sayang)",
  "Rino wengi aku tansah kelingan, pengenku kowe tak sayang(Siang malam aku selalu teringat, inginku kau kucintai)",
  "Prinsipku saiki mung maju tak gentar, mundur tak ganjel, sisane serahke Gusti Allah(Prinsipku sekarang maju tak gentar, mundur diganjel, sisanya pasrahkan ke Allah)",
  "Kowe wis tak wanti wanti ojo nganti ninggal janji, ojo nganti medot taline asmoro, welasno aku sing nunggu awakmu nganti awak ku tinggal balung karo kulit(Kamu sudah aku ingatkan jangan melupakan janji, jangan sampai memutuskan ikatan cinta ini, ingatlah diriku yang menunggu dirimu sampai badanku hanya tersisa tulang dan kulit)",
  "Gusti Allah paring pitedah bisa lewat bungah, bisa lewat susah(Allah memberikan petunjuk bisa melalui bahagia, bisa melalui derita)",
  "Tresno iku kadang koyo criping telo Iso ajur nek ora ngati-ati le nggowo(Cinta terkadang seperti keripik singkong, bisa hancur jika tidak hati-hati dibawa)",
  "Mergo nyawang fotomu, dadi nyungsep neng lendutan(Gara-gara melihat fotomu, jadi nyungsep di lumpur)",
  "Aku ora pernah ngerti opo kui tresno, kajaba sak bare ketemu karo sliramu(Aku tidak pernah tahu cinta itu apa, kecuali setelah bertemu denganmu)",
  "Cinta dudu perkoro sepiro kerepe kowe ngucapke, tapi sepiro akehe seng mbok buktike(Cinta bukan perkara seberapa sering kamu mengucapkannya, tapi seberapa banyak kamu membuktikannya)",
  "Suket teles kudanan sore, atiku ngenes mikirna kowe(Rumput basah kehujanan di sore hari, hatiku sakit karena memikirkan kamu terus)",
  "Pengenku, aku iso muter wektu Supoyo aku iso nemokne kowe lewih gasik Ben lewih dowo wektuku kanggo urip bareng sliramu(Aku berharap, aku bisa memutar waktu kembali Di mana aku bisa lebih awal menemukan dan mencintaimu lebih lama)",
  "Mbangun kromo ingkang satuhu, boten cekap bilih ngagem sepisan roso katresnan Hananging butuh pirang pirang katresnan lumeber ning pasangan uripmu siji kui(Pernikahan yang sukses tidak membutuhkan sekali jatuh cinta, tetapi berkali kali jatuh cinta pada orang yang sama)",
  "Kowe ngeluh etuk wong seng salah terus, coba kowe luwih peka sitik pas dicedakke karo uwong seng bener yo(Kamu terus mengeluh dapat orang yang salah terus, coba kamu lebih peka sedikit ketika bersama orang yang benar)",
  "Witing tresno jalaran soko kulino Witing mulyo jalaran wani rekoso(Bahwa cinta itu tumbuh lantaran ada kebiasaan, kemakmuran itu timbul karena berani bersusah dahulu)",
  "Sek penting kowe bahagia, tapi mung karo aku Ora karo wong liya(Yang penting kamu bahagia, tapi cuma sama aku Bukan sama orang lain)",
  "Kadang mripat iso salah ndelok, kuping iso salah krungu, lambe iso salah ngomong, tapi ati ora bakal iso diapusi(Terkadang mata bisa salah melihat, telinga bisa salah mendengar, mulut bisa salah mengucap, tapi hati tak bisa dibohongi dan membohongi)",
  "Semoga jodohku adalah orang yang selalu aku sebut dalam doaku tiap hari",
  "Cinta memang aneh, bahkan kau tak bisa memilih dengan siapa kau akan jatuh cinta",
  "Aku tetap mencintai kamu, meski mungkin jiwa ini tak akan pernah saling memiliki",
  "Aku memilih untuk sendiri, bukan karena menunggu yang sempurna, tetapi butuh yang tak pernah menyerah",
  "Seorang yang single diciptakan bersama pasangan yang belum ditemukannya",
  "Jomblo Mungkin itu cara Tuhan untuk mengatakan 'Istirahatlah dari cinta yang salah'",
  "Jomblo adalah anak muda yang mendahulukan pengembangan pribadinya untuk cinta yang lebih berkelas nantinya",
  "Aku bukan mencari seseorang yang sempurna, tapi aku mencari orang yang menjadi sempurna berkat kelebihanku",
  "Pacar orang adalah jodoh kita yang tertunda",
  "Jomlo pasti berlalu Semua ada saatnya, saat semua kesendirian menjadi sebuah kebersamaan dengannya kekasih halal Bersabarlah",
  "Romeo rela mati untuk Juliet, Jack mati karena menyelamatkan Rose Intinya, kalau tetap mau hidup, jadilah single",
  "Aku mencari orang bukan dari kelebihannya, tapi aku mencari orang dari ketulusan hatinya",
  "Jodoh bukan sendal jepit, yang kerap tertukar Jadi teruslah berada dalam perjuangan yang semestinya",
  "Jika kamu penikmat kopi dan senja, maka izinkan aku mencintaimu tanpa henti dan jeda",
  "Tuhan baik banget ya, aku minta bahagia, dikasihnya kamu",
  "Kalau mawar itu warna merah, kalau hadirmu itu warna-warni dalam hidupku",
  "Kalau kamu jadi senar gitar, aku nggak mau jadi gitarisnya Karena aku nggak mau mutusin kamu",
  "Bila mencintaimu adalah ilusi, maka izinkan aku berimajinasi selamanya",
  "Sayang tugas aku hanya mencintaimu, bukan melawan takdir",
  "Saat aku sedang bersamamu rasanya 1 jam hanya 1 detik, tetapi jika aku jauh darimu rasanya 1 hari menjadi 1 tahun",
  "Kolak pisang tahu sumedang, walau jarak membentang cintaku takkan pernah hilang",
  "Aku ingin menjadi satu-satunya, bukan salah satunya",
  "Aku tidak bisa berjanji untuk menjadi yang baik, tapi aku berjanji akan selalu mendampingi kamu",
  "Kalau aku jadi wakil rakyat aku pasti gagal, gimana mau mikirin rakyat kalau yang selalu ada dipikiran aku hanyalah dirimu",
  "Lihat kebunku, penuh dengan bunga Lihat matamu, hatiku berbunga-bunga",
  "Berjanjilah untuk terus bersamaku sekarang, esok, dan selamanya",
  "Kangen kamu itu sudah jadi hobi aku",
  "Kamu salah satu alasanku untuk beli paket internet, kangen terus soalnya",
  "Rindu tak akan pernah jemu, membuat candu, membuat malam semakin biru, kamu",
  "Rindu tidak hanya muncul karena jarak yang terpisah, tapi juga karena keinginan yang tidak terwujud",
  "Kamu tidak akan pernah jauh dariku, kemanapun aku pergi kamu selalu ada, karena kamu selalu di hatiku, yang jauh hanya raga kita bukan hati kita",
  "Aku tahu dalam setiap tatapanku, kita terhalang oleh jarak dan waktu, tapi aku yakin kalau nanti kita pasti bisa bersatu",
  "Merindukanmu tanpa pernah bertemu sama halnya dengan menciptakan lagu yang tak pernah ternyayikan",
  "Ada kalanya jarak selalu menjadi penghalang antara aku sama kamu, tapi tetap saja di hatiku kita selalu dekat",
  "Jika hati ini tak mampu membendung segala kerinduan, apa daya tak ada yang bisa aku lakukan selain mendoakanmu",
  "Mungkin di saat ini aku hanya bisa menahan kerinduan ini Sampai tiba saatnya nanti aku bisa bertemu dan melepaskan kerinduan ini bersamamu",
  "Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu",
  "Dalam dinginnya malam, tak kuingat lagi; Berapa sering aku memikirkanmu juga merindukanmu",
  "Merindukanmu itu seperti hujan yang datang tiba-tiba dan bertahan lama Dan bahkan setelah hujan reda, rinduku masih terasa",
  "Mau tanggal merah sekalipun, aku nggak akan libur untuk mikirin kamu",
  "Teringat kisah cinta di masa SMA yang begitu indah dan menyenangkan bersamamu",
  "Bolehkah aku belajar mencintaimu mengalahkan Matematika dan Fisika?",
  "Tahu gak perbedaan pensil sama wajah kamu? Kalau pensil tulisannya bisa dihapus, tapi kalau wajah kamu gak akan ada yang bisa hapus dari pikiran aku",
  "Bukan Ujian Nasional besok yang harus aku khawatirkan, tapi ujian hidup yang aku lalui setelah kamu meninggalkanku",
  "Satu hal kebahagiaan di sekolah yang terus membuatku semangat adalah bisa melihat senyumanmu setiap hari",
  "Kamu tahu gak perbedaanya kalau ke sekolah sama ke rumah kamu? Kalo ke sekolah pasti yang di bawa itu buku dan pulpen, tapi kalo ke rumah kamu, aku cukup membawa hati dan cinta",
  "Aku gak sedih kok kalo besok hari Senin, aku sedihnya kalau gak ketemu kamu",
  "Momen cintaku tegak lurus dengan momen cintamu Menjadikan cinta kita sebagai titik ekuilibrium yang sempurna",
  "Aku rela ikut lomba lari keliling dunia, asalkan engkau yang menjadi garis finish-nya",
  "PR-ku adalah merindukanmu Lebih kuat dari Matematika, lebih luas dari Fisika, lebih kerasa dari Biologi",
  "Cintaku kepadamu itu bagaikan metabolisme, yang gak akan berhenti sampai mati",
  "Aku tanpamu bagaikan ambulans tanpa wiuw wiuw wiuw",
  "Kamu nggak capek? Tiap kali aku memejamkan mata muncul kamu terus",
  "Kamu tahu nggak apa persamaannya kamu sama AC? Sama-sama bikin aku sejuk",
  "Kalau jelangkungnya kaya kamu, dateng aku jemput, pulang aku anter, deh",
  "Makan apapun aku suka asal sama kamu, termasuk makan hati",
  "Cinta itu kaya hukuman mati Kalau nggak ditembak, ya digantung",
  "Mencintaimu itu kayak narkoba: sekali coba jadi candu, gak dicoba bikin penasaran, ditinggalin bikin sakau",
  "Gue paling suka ngemil karena ngemil itu enak Apalagi ngemilikin kamu sepenuhnya",
  "Dunia ini cuma milik kita berdua Yang lainnya cuma ngontrak",
  "Bagi aku, semua hari itu adalah hari Selasa Selasa di Surga bila dekat denganmu",
  "Bagaimana kalau kita berdua jadi komplotan penjahat? Aku curi hatimu dan kamu curi hatiku",
  "Kamu itu seperti kopi yang aku seruput pagi ini Pahit, tapi bikin nagih",
  "Aku sering cemburu sama lipstikmu Dia bisa nyium kamu tiap hari, dari pagi sampai malam",
  "Hanya mendengar namamu saja sudah bisa membuatku tersenyum seperti orang bodoh",
  "Aku tau teman wanitamu bukan hanya satu dan menyukaimu pun bukan hanya aku",
  "Semenjak aku berhenti berharap pada dirimu, aku jadi tidak semangat dalam segala hal",
  "Denganmu, jatuh cinta adalah patah hati paling sengaja",
  "Sangat sulit merasakan kebahagiaan hidup tanpa kehadiran kamu disisiku",
  "Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu",
  "Sendainya kamu tahu, sampai saat ini aku masih mencintaimu",
  "Terkadang aku iri sama layangan Talinya putus saja masih dikejar kejar dan gak rela direbut orang lain",
  "Aku tidak tahu apa itu cinta, sampai akhirnya aku bertemu denganmu Namun, saat itu juga aku tahu rasanya patah hati",
  "Mengejar itu capek, tapi lebih capek lagi menunggu Menunggu kamu menyadari keberadaanku",
  "Jangan berhenti mencinta hanya karena pernah terluka Karena tak ada pelangi tanpa hujan, tak ada cinta sejati tanpa tangisan",
  "Aku punya sejuta alasan untuk melupakanmu, tapi tak ada yang bisa memaksaku untuk berhenti mencintaimu",
  "Terkadang seseorang terasa sangat bodoh hanya untuk mencintai seseorang",
  "Kamu adalah patah hati terbaik yang gak pernah aku sesali",
  "Bukannya tak pantas ditunggu, hanya saja sering memberi harapan palsu",
  "Sebagian diriku merasa sakit, mengingat dirinya yang sangat dekat, tapi tak tersentuh",
  "Hal yang terbaik dalam mencintai seseorang adalah dengan diam-diam mendoakannya",
  "Kuharap aku bisa menghilangkan perasaan ini secepat aku kehilanganmu",
  "Demi cinta kita menipu diri sendiri Berusaha kuat nyatanya jatuh secara tak terhormat",
  "Anggaplah aku rumahmu, jika kamu pergi kamu mengerti kemana arah pulang Menetaplah bila kamu mau dan pergilah jika kamu bosan",
  "Aku bingung, apakah aku harus kecewa atu tidak? Jika aku kecewa, emang siapa diriku baginya? Kalau aku tidak kecewa, tapi aku menunggu ucapannya",
  "Rinduku seperti ranting yang tetap berdiri Meski tak satupun lagi dedaunan yang menemani, sampai akhirnya mengering, patah, dan mati",
  "Kurasa kita sekarang hanya dua orang asing yang memiliki kenangan yang sama",
  "Buatlah aku bisa membencimu walau hanya beberapa menit agar tidak terlalu berat untuk melupakanmu",
  "Aku mencintaimu dengan segenap hatiku, tapi kau malah membagi perasaanmu dengan orang lain",
  "Mencintaimu mungkin menghancurkanku, tapi entah bagaimana meninggalkanmu tidak memperbaikiku",
  "Kamu adalah yang utama dan pertama dalam hidupku, tapi aku adalah yang kedua bagimu",
  "Jika kita hanya bisa dipertemukan dalam mimpi, aku ingin tidur selamanya",
  "Melihatmu bahagia adalah kebahagiaanku, walaupun bahagiamu tanpa bersamaku",
  "Aku terkadang iri dengan sebuah benda Tidak memiliki rasa namun selalu dibutuhkan Berbeda dengan aku yang memiliki rasa, namun ditinggalkan dan diabaikan",
  "To the person I stayed up with until 3 am I should've slept",
  "Love is being stupid together",
  "I love you more today than yesterday, and I will continue to fall in love with you, over and over again, until the day I die",
  "I want someone who will look at me the same way I look at chocolate cake",
  "I love you with every beat of my heart",
  "You taught me how to love, but not how to stop",
  "Loving you was my favorite mistake",
  "You broke my heart But I still love you with all the pieces",
  "In past, you are like an oxygen for me and I always need you to stay alive But now, you are like a carbon dioxide, go out from me",
  "My life used to be in dull grey Thank you, now it is in brighter colors",
  "Roses are red Violets are blue I know that it's often said But I really love you",
  "If dreaming is the only way to be with you, then i'il never open my eyes",
  "My favorite place is inside your hug, even you leave me",
  "Bagaimana mungkin aku berpindah jika hanya padamu hatiku bersinggah?",
  "Kenangan tentangmu sudah seperti rumah bagiku Sehingga setiap kali pikiranku melayang, pasti ujung-ujungnya akan selalu kembali kepadamu",
  "Kenapa tisue bermanfaat? Karena cinta tak pernah kemarau - Sujiwo Tejo",
  "Kalau mencintaimu adalah kesalahan, yasudah, biar aku salah terus saja",
  "Sejak kenal kamu, aku jadi pengen belajar terus deh Belajar jadi yang terbaik buat kamu",
  "Ada yang bertingkah bodoh hanya untuk melihatmu tersenyum Dan dia merasa bahagia akan hal itu",
  "Aku bukan orang baik, tapi akan belajar jadi yang terbaik untuk kamu",
  "Kita tidak mati, tapi lukanya yang membuat kita tidak bisa berjalan seperti dulu lagi",
  "Keberadaanmu bagaikan secangkir kopi yang aku butuhkan setiap pagi, yang dapat mendorongku untuk tetap bersemangat menjalani hari",
  "Aku mau banget ngasih dunia ke kamu Namun, karena itu nggak mungkin, maka aku akan kasih hal yang paling penting dalam hidupku, yaitu duniaku",
  "Mending sing humoris tapi manis, ketimbang sok romantis tapi akhire tragis",
  "Ben akhire ora kecewa, dewe kudu ngerti kapan waktune berharap lan kapan kudu mandeg",
  "Aku ki wong Jowo seng ora ngerti artine 'I Love U', tapi aku ngertine mek 'Aku tresno awakmu'",
  "Ora perlu ayu lan sugihmu, aku cukup mok setiani wes seneng ra karuan",
  "Cintaku nang awakmu iku koyok kamera, fokus nang awakmu tok liyane mah ngeblur",
  "Saben dino kegowo ngimpi tapi ora biso nduweni",
  "Ora ketemu koe 30 dino rasane koyo sewulan",
  "Aku tanpamu bagaikan sego kucing ilang karete Ambyar",
  "Pengenku, Aku iso muter wektu Supoyo aku iso nemokne kowe lewih gasik Ben Lewih dowo wektuku kanggo urip bareng sliramu",
  "Aku ora pernah ngerti opo kui tresno, kajaba sak bare ketemu karo sliramu",
  "Cinta Aa ka Neng moal leungit-leungit sanajan aa geus kawin deui",
  "Kasabaran kaula aya batasna, tapi cinta kaula ka anjeun henteu aya seepna",
  "Kanyaah akang moal luntur najan make Bayclean",
  "Kenangan endah keur babarengan jeung anjeun ek tuluy diinget-inget nepi ka poho",
  "Kuring moal bakal tiasa hirup sorangan, butuh bantosan jalmi sejen",
  "Nyaahna aa ka neg teh jiga tukang bank keur nagih hutang (hayoh mumuntil)",
  "Kasabaran urang aya batasna, tapi cinta urang ka maneh moal aya beakna",
  "Hayang rasana kuring ngarangkai kabeh kata cinta anu aya di dunya ieu, terus bade ku kuring kumpulkeun, supaya anjeun nyaho gede pisan rasa cinta kuring ka anjeun",
  "Tenang wae neng, ari cinta Akang mah sapertos tembang krispatih; Tak lekang oleh waktu",
  "Abdi sanes jalmi nu sampurna pikeun anjeun, sareng sanes oge nu paling alus kanggo anjeun Tapi nu pasti, abdi jalmi hiji-hijina nu terus emut ka anjeun",
  "Cukup jaringan aja yang hilang, kamu jangan",
  "Sering sih dibikin makan hati, tapi menyadari kamu masih di sini bikin bahagia lagi",
  "Musuhku adalah mereka yang ingin memilikimu juga",
  "Banyak yang selalu ada, tapi kalo cuma kamu yang aku mau, gimana?",
  "Jam tidurku hancur dirusak rindu",
  "Cukup China aja yang jauh, cinta kita jangan",
  "Yang penting itu kebahagiaan kamu, aku sih gak penting",
  "Cuma satu keinginanku, dicintai olehmu",
  "Aku tanpamu bagaikan ambulans tanpa wiuw wiuw wiuw",
  "Cukup antartika aja yang jauh Antarkita jangan",
]



  # motivasi text
MOTIVASI = [
"di setiap kelebihan pasti ada kembalian",
"cobaan memang banyak kalo dikit itu cobain",
"kalau orang lain bisa mengapa harus saya, kalau orang lain gak bisa apalagi saya",
"lebih baik menjauh daripada tersakiti begitulah caraku menggoreng ikan",
"sholat itu 5 waktu, bukan kalo ada waktu",
"tetaplah membalas budi, walau budi nggak salah",
"jika kamu bilang cari duit itu sulit, percayalah,nagih utang jauh lebih sulit",
"jika hidupmu malang, cobalah ke Bali",
"ke masjid itu sampai tua bukan nunggu tua",
"ingat kawan sakit gigi dan sakit hati berawal dari yang 'manis manis'",
"kesempatan tidak datang 2 kali kecuali remedial",
"hidup cuman sekali kalo dua kali namanya hidup-hidup",
"kalian mau tau kenapa pria sejati itu kebanyakan sibuk?  ok nanti aku jelasin, lagi sibuk soalnya.",
"sibuk mencari kesibukan yang tidak menyibukan",
"masa depan mu tidak secerah 'hp bapakku'",
"disaat masalah tidak ada jalan keluarnya, maka kita yang keluar jalan-jalan",
"Pekerjaan akan lebih mudah jika tidak dikerjakan",
"Istiqomah itu berat, yang ringan mah istirahat.",
"dunia ini berputar, pantesan saya pusing",
"Hidup itu berjalan kalo capek naik gojek aja",
"dunia punya cerita yg cerita bukan saya",
"ingin tidak mau jadi beban keluarga yaa keluar kk",
"'sesuatu yang berlebihan itu tidak baik kecuali' uang",
"cinta itu hanya bertepuk sebelah tangan, kalau tepuk dua tangan jadi tepuk pramuka",
"kalau pekerjaan mu berat cari lah yg ringan",
"anda punya masalah Ya itu bukan urusan saya, karena klau saya ikut akan jadi masalah buat saya",
"bermimpi adalah hal terbaik, maka dari itu saya sering tidur.",
"ibu dan bapak kalian nikah di tanggal yang sama",
"diam tidak akan menyelesaikan masalah, tapi diam juga tidak membuat masalah",
"jika kamu gagal jadi orang sukses. tenanglah. setidaknya kamu telah sukses jadi orang gagal.",
"aku tulus, tapi aku gabisa nyanyi",
"hidup memang banyak ujian , kalau banyak cucian itu Laundry",
"pengen ngejar mimpi tapi males lari",
"tanpa kalian sadari,kalian itu udah sadar",
"kalau roda bisa berhenti kenapa harus berputar?",
"jika kamu gagal maka cobalah lagi, siapa tau gagal lagi",
"kamu tau kiko? Enak tau",
"prot² lebih menyenangkan dari pada janji kawan",
"Hari ini dan esok harinya untuk kita berdua , tapi hari selanjutnya untuk siapa?",
"aku cuma punya motor supra, kalo kamu suka sama ninja. sama aku juga",
"jadilah murid teladan, datangnya telat pulang duluan",
"penyesalan itu di akhir kalo di awal itu pendaftaran",
"didewasakan oleh film dewasa",
"jangan ngurusin saya, saya udah kurus",
"tanpa saya, warga Indonesia kurang satu",
"menyukai tidak harus memiliki, itulah caraku melihat shopee",
"dikuburan itu sepi, kalo rame lanjut part 2",

"Kerja keraslah sampai tetangga berpikir rezekimu hasil dari pesugihan.",
"Berhentilah mencari orang yang sempurna. Cukup cari orang yang punya uang, mobil, dan rumah.",
"Sukses berawal dari mimpi. Oleh karena itu mari kita perbanyak tidur.",
"Kamu tidak butuh kata-kata motivasi, yang kamu butuhkan adalah kata 'diskon besar-besaran'.",
"Jangan mengulangi kesalahan yang sama. Masih banyak kesalahan-kesalahan lain yang perlu dicoba.,
"Di mana ada kesempatan, di situ ada dana umum.",
"Namanya juga hidup. Pasti banyak cobaan. Kalau banyak cucian ya laundry.",
"Masalah bisa membuat kita semakin dewasa, maka sering-seringlah bermasalah.",
"Kalau mau punya pasangan yang bisa bikin hidup kamu bergelimang harta, jangan cari pasangan, carilah pesugihan.",
"Betapa banyak manusia yang masih hidup dalam kelalaian. Sedangkan kain kafannya sedang ditenun.",
"Pengetahuan itu seperti pakaian dalam, jika memang kamu punya tak usah dipamerkan.",
"Kepada matematika, dewasalah dan selesaikan persoalanmu sendiri. Aku sudah lelah menyelesaikan masalahmu.",
"Sekali mendayung, dua tiga hari pegelnya nggak ilang-ilang.",
"Saat hidup menutup pintu untukmu, buka lagi saja. Itu hanya pintu, itulah cara kerjanya.",
 "Jangan meresapi sebuah kegagalan. Meres baju aja capeknya minta ampun, apalagi meres-sapi.",
"Sabar aja lah ya, hati kamu itu kan kaya tango. Berapa lapis? Ratusan.",
 "Diam tak akan menyelesaikan masalah, tapi diam juga tak akan menimbulkan masalah.",
"Belajar dari bulu ketek walaupun selalu terhimpit tapi tetap tegar bertahan dan tetap tumbuh.",
 "Seberat apa pun masalahmu, jangan ditimbang. Nggak bakalan laku.",
"Sahabat super, jika ingin terlihat ganteng, bergaullah dengan orang jelek.",
 "Cinderella adalah bukti bahwa sepasang sepatu baru dapat mengubah hidupmu.",
"Hormati orang tuamu. Mereka lulus sekolah tanpa Google.",
"Ketika hidup menempatkanmu dalam situasi yang sulit, jangan katakan 'Mengapa saya?', katakan 'Cobalah saya'.",
"Saya ingin menjadi seperti ulat. Makan banyak. Tidur sebentar. Bangun cantik.",
"Bekerjalah sampai rekening bankmu terlihat seperti nomor telepon.",
"Jika kamu tidak merancang rencana hidupmu sendiri, kemungkinan besar kamu akan jatuh ke dalam rencana orang lain. Dan coba tebak apa yang mereka rencanakan untukmu? Tidak banyak.",
"Kerja tim berarti tidak pernah harus menanggung semua kesalahan sendiri.",
"Berpikirlah seperti proton. Selalu positif.",
"Jadi ternyata menjadi dewasa sebenarnya hanya Googling bagaimana melakukan sesuatu.",
"Tidak semua badai datang untuk mengganggu hidupmu. Beberapa datang untuk membersihkan jalanmu.",
"Jalan menuju sukses dipenuhi banyak tempat parkir yang menggoda.",
"Hidup adalah seni menggambar tanpa penghapus.",
"Kebahagiaan hanyalah kesedihan yang belum terjadi.",
"Jika ukuran benar-benar penting, gajah sudah lama menjadi raja hutan.",
"Hidup bergerak sangat cepat. Jika kamu tidak berhenti dan melihat-lihat sesekali, kamu bisa melewatkannya.",
 "Tidur siang terdengar sangat kekanak-kanakan. Aku lebih suka menyebutnya jeda kehidupan horizontal.",
"Kamu tidak bisa membuat semua orang bahagia. Kamu bukan cokelat.",
"Hidup itu seperti sebuah acara televisi yang sangat panjang tanpa remote control.",
"Jika kamu merasa kesepian, matikan lampu dan tontonlah film horor. Maka kamu tidak akan merasakan kesepian lagi.",
 "Tuhan, tolong beri aku kesabaran. Kalau Engkau beri aku kekuatan, mungkin aku akan memukul orang itu tepat di wajahnya.",
 "Sabar memang sulit karena hadiahnya surga. Coba kalau gampang, paling hadiahnya payung.",
"Tidak ada yang abadi, kecuali perubahan dan pengeluaran.",
"Duit memang nggak dibawa mati. Tapi kalau nggak ada duit, berasa mau mati.",
"Hidup itu sudah susah dan kadang banyak masalah. Untuk itulah, terkadang hidup hanya perlu ditertawakan saja.",
"Hanya karena kamu benar, bukan berarti aku salah. Kamu hanya belum pernah hidup di posisiku.",
 "Cantik itu relatif, tergantung letak kamera dan intensitas cahaya.",
"Lembaran uang itu bukan segalanya. Masih ada kartu kredit dan yang lainnya.",
 "Makanan semahal apa pun tidak akan terasa mahal jika tidak dibeli.",
"Manusia boleh berencana, tapi saldo juga yang menentukan.",
"Kenapa move on itu susah? Karena dari SD sampai sekarang yang dipelajari adalah menghafal atau mengingat bukan melupakan.",
"Contohlah tukang parkir. Meskipun punya banyak mobil, ia tak pernah sombong karena tahu itu semua hanya titipan.",
 "Jika ada orang yang menyebutmu jelek. Jangan putus asa. Karena belum tentu orang itu bohong.",
 "Jika ada seseorang yang meledekmu jelek, santai saja. Bilang padanya kalau kamu bukan cermin.",
 "Lagi konsen cari uang, buat beli nasi padang. Sisanya buat beli pajero sport.",
 "Motivasi tidak akan bertahan lama. Mandi juga tidak bertahan lama. Itulah alasan mengapa kami menganjurkannya setiap hari.",
"Ada yang tidak bisa dibeli di dunia ini yaitu kesehatan, kebahagiaan, dan sinyal HP.",
"Selalu ikuti kata hatimu. Tapi jangan lupa bawa juga otakmu.",
"Katanya habis gelap terbitlah terang. Ternyata, kalau belum terang, belum mau pulang.",
 "Orang bodoh lebih mudah bahagia, dengan kebodohannya.",
"Setinggi-tingginya bangau terbang. Akhirnya akan jadi kecap juga.",

"Saya tidak bisa mengubah arah angin, namun saya bisa menyesuaikan pelayaran saya untuk selalu menggapai tujuan saya.",
"Tanpa sasaran dan rencana meraihnya, kamu seperti kapal yang berlayar tanpa tujuan.",
"Banyak orang gagal dalam kehidupan, bukan karena kurangnya kemampuan, pengetahuan, atau keberanian, namun hanya karena mereka tidak pernah mengatur energinya pada sasaran.",
"Jika kamu ingin bahagia, tetapkan sasaran yang membangkitkan pikiran, membebaskan energi, dan menginspirasi harapanmu.",
"Tindakan menyalahkan hanya akan membuang waktu. Sebesar apapun kesalahan yang kamu timpakan ke orang lain, dan sebesar apapun kamu menyalahkannya, hal tersebut tidak akan mengubahmu.",
"Jangan tanyakan pada dirimu apa yang dibutuhkan dunia. Bertanyalah apa yang membuat kamu merasa hidup, kemudian kerjakan. Karena yang dibutuhkan dunia adalah orang yang antusias." ,
"Janganlah menganggap remeh hal-hal yang terdekat dengan hatimu. Rangkullah mereka seperti sama berharganya dengan hidupmu, karena tanpa mereka hidup adalah sia-sia." ,
 "Perubahan itu menyakitkan, Ia menyebabkan orang merasa tidak aman, bingung, dan marah. Orang menginginkan hal seperti sediakala, karena mereka ingin hidup yang mudah." ,
"Orang yang lemah tidak mampu memaafkan. Memaafkan adalah ciri orang yang kuat.",
"Cara paling mendasar dan kuat untuk terhubung dengan orang lain adalah dengan mendengarkan. Cukup Dengarkan. Mungkin hal terpenting yang bisa kita berikan kepada orang lain adalah perhatian kita." ,
"Ingat, ini hanya hari yang buruk, bukan kehidupan yang buruk.",
"Apapun dirimu, jadilah yang terbaik." ,
"Pikiran yang baik dan hati yang baik selalu merupakan kombinasi yang hebat." ,
"Satu-satunya cara untuk mencapai yang tidak mungkin adalah percaya bahwa itu mungkin." ,
"Aku tidak tahu semua yang mungkin akan datang, tetapi apa pun yang akan terjadi, aku akan melakukannya sambil tertawa." ,
"Jangan biarkan rasa takut kalah lebih besar daripada kegembiraan saat menang." ,
"Ketika memiliki mimpi, kamu harus meraihnya dan tidak pernah melepaskannya.",
 "Tidak ada yang tidak mungkin. Kata itu sendiri mengatakan 'Saya mungkin!'",
"Tidak ada yang tidak mungkin bagi mereka yang mau berusaha.",
"Kabar buruknya adalah waktu berlalu begitu saja. Kabar baiknya adalah kamu adalah pilotnya.",
"Hidup memiliki semua tikungan dan belokan itu. Kamu harus berpegangan erat-erat dan pergilah.",
"Tetap menghadapkan wajah selalu ke arah sinar matahari, dan bayangan akan jatuh di belakangmu.",
 "Kamu tidak selalu membutuhkan rencana. Terkadang kamu hanya perlu bernapas, percaya, melepaskan dan melihat apa yang terjadi.",
 "Kamu bisa menjadi segalanya. Kamu bisa menjadi orang yang tidak terbatas jumlahnya. ",
"Keyakinan menciptakan fakta yang sebenarnya.",
"Orang yang memiliki sasaran sukses karena mereka tahu ke mana akan pergi.",
 "Ambillah risiko yang lebih besar dari apa yang dipikirkan orang lain aman. Berilah perhatian lebih dari apa yang orang lain pikir bijak. Bermimpilah lebih dari apa yang orang lain pikir masuk akal.",
"Satu-satunya batasan untuk meraih mimpi kita adalah keragu-raguan kita akan hari ini. Marilah kita maju dengan keyakinan yang aktif dan kuat.",
"Seperti bergulat melawan seekor gorila. Kamu tidak akan berhenti ketika lelah, kamu berhenti ketika gorila tersebut lelah.",
"Sebuah permata tidak akan dapat dipoles tanpa gesekan, demikian juga seseorang tidak akan menjadi sukses tanpa tantangan.",
 "Jika kamu menginginkan sesuatu yang belum pernah dimiliki dalam hidupmu. Kamu harus melakukan sesuatu yang belum pernah dilakukan sebelumnya.",
"Bangun dan wujudkan mimpimu atau orang lain akan memperkerjakanmu untuk membangun mimpi mereka.",
"Kesuksesan tidak menemukamu karena kamu yang harus keluar dan meraihnya.",
"Seorang pemenang adalah pemimpi yang tidak pernah menyerah.",
"Semua mimpi kita bisa jadi kenyataan, jika kita memiliki keberanian untuk mengejarnya.",
"Sukses bukanlah akhir, kegagalan bukanlah fatal, yang terpenting adalah keberanian untuk melanjutkan.",
"Orang yang memiliki sasaran akan menjadi sukses karena mereka tahu ke mana akan pergi.",
 "Saya tidak bisa mengubah arah angin, namun saya bisa menyesuaikan pelayaran saya untuk selalu menggapai tujuan saya.",
 "Gagal itu makanan sehari-hari. Itu biasa, yang penting bagimana kamu menyikapinya. Evaluasi. Bangkit. Gagal lagi? Bangkit lagi!",
"Jika tindakanmu menginspirasi orang lain untuk bermimpi lebih banyak, belajar lebih banyak, berbuat lebih banyak, dan menjadi lebih sukses, kamu adalah seorang pemimpin.",
"Jangan pernah bermimpi untuk sukses, tapi kerjakan sesuatu untuk meraih kesuksesan." ,
 "Kesuksesan bersumber dari perbuatan. Orang yang sukses terus melakukan usaha. Orang sukses bahkan membuat kesalahan, namun mereka tidak berhenti usaha.",
 "Jalan menuju sukses dan jalan menuju kegagalan hampir persis sama.",
 "Kita tidak bisa memecahkan masalah dengan cara berpikir yang kita gunakan ketika kita menemukan masalah itu." ,
"Belajarlah seolah-olah kamu akan hidup selamanya, hiduplah seolah-olah kamu akan mati besok.",
"Jauhi orang-orang yang mencoba meremehkan ambisimu. Pikiran kecil akan selalu melakukan itu, tetapi pikiran besar akan memberi perasaan bahwa kamu juga bisa menjadi hebat.",
"Ketika memberikan kegembiraan kepada orang lain, kamu mendapatkan lebih banyak kegembiraan sebagai balasannya. Kamu harus memikirkan kebahagiaan yang bisa kamu berikan.",
 "Ketika kamu mengubah pikiran, ingatlah untuk juga mengubah duniamu juga.",
 "Hanya ketika kita mengambil peluang, ketika hidup kita membaik. Risiko awal dan paling sulit yang perlu kita ambil adalah menjadi jujur.",
"Pendidikan bukan cuma pergi ke sekolah dan mendapatkan gelar. Tapi, juga soal memperluas pengetahuan dan menyerap ilmu kehidupan.",
"Janganlah pernah menyerah ketika kamu masih mampu berusaha lagi. Tidak ada kata berakhir sampai kamu berhenti mencoba.",
"Pertama kita membentuk kebiasaan dan kebiasaan akan membentuk kita. Kalahkan kebiasaan burumu, atau mereka akan mengalahkanmu dengan mudah.",
"Jangan menyerah. Hal-hal besar membutuhkan waktu. Bersabarlah.",
"Optimisme adalah iman yang menuntunmu ke pencapaian." ,
"Kamu hanya gagal saat kamu berhenti mencoba.",
"Jika kamu tidak pernah gagal, kamu tidak akan pernah mencoba apapun yang baru.",
"Sulit untuk mengalahkan orang yang tidak pernah menyerah.",
"Belajar tidak pernah melelahkan pikiran.",
"Berjuang sampai napas terakhir.",
"Jika kamu benar-benar menginginkan sesuatu, jangan menunggu untuk itu – ajari dirimu untuk tidak sabar.",
"​Sukses adalah jumlah dari usaha-usaha kecil, berulang-ulang hari demi hari." ,
"Bila memiliki banyak harta, kita akan menjaga harta. Namun, jika memiliki banyak ilmu, maka ilmulah yang akan menjaga kita.",
"Pendidikan adalah senjata paling ampuh yang bisa digunakan untuk mengubah dunia.",
"Pembelajaran tidak didapat dengan kebetulan. Ia harus dicari dengan semangat dan disimak dengan tekun." ,
"Orang bijak belajar ketika mereka bisa. Orang bodoh belajar ketika mereka terpaksa.",
"Agama tanpa ilmu adalah buta. Ilmu tanpa agama adalah lumpuh.",
"Masa depan memang tak pasti, tapi kalo kita belajar dengan bekerja keras, kita akan sukses.",
"Barangsiapa tidak mau merasakan pahitnya belajar, ia akan merasakan hinanya kebodohan sepanjang hidupnya." ,
"Ikhlaslah belajar. Bahkan yang paling berilmu dan bijak di antara kita masih rajin belajar.",
"Guru memang membantu kita dalam membuka pintu, tetapi kita sendirilah yang harus memasukinya.",
"Hal yang indah tentang belajar adalah tidak ada yang bisa mengambilnya darimu.",
"Pikiran bukanlah wadah untuk diisi, tetapi api untuk dinyalakan.",
"Penundaan membuat hal-hal mudah menjadi sulit dan hal-hal sulit menjadi lebih sulit.",
"Kamu tidak harus hebat untuk memulai, tapi kamu harus memulai untuk menjadi hebat.",
"Pakar dalam segala hal dulunya adalah seorang pemula.",
"Motivasi adalah apa yang membuat kamu memulai. Kebiasaan adalah sesuatu yang membuatmu terus maju.",
 "Dia yang bertanya adalah bodoh selama 5 menit; dia yang tidak bertanya akan tetap bodoh selamanya." ,
"Keraguan membunuh lebih banyak mimpi daripada kegagalan.",
"Semakin banyak kamu membaca, semakin banyak hal yang akan kamu ketahui, semakin banyak yang kamu pelajari, semakin banyak tempat yang akan kamu kunjungi." ,
"Aku tidak terlalu memikirkan orang yang hari ini tidak lebih bijaksana daripada kemarin. ",
 "Belajar adalah harta karun yang akan mengikuti pemiliknya kemanapun." ,
"Selalu jalani hidup seolah-olah kamu memiliki sesuatu yang baru untuk dipelajari dan kamu akan melakukannya.",
"Siapa pun yang berhenti belajar sudah tua, baik pada usia dua puluh atau delapan puluh tahun.",
"Investasi dalam pengetahuan membayar bunga terbaik.",
"Satu-satunya orang yang berpendidikan adalah orang yang telah belajar bagaimana belajar dan berubah.",
"Pikiran manusia, sekali diregangkan oleh ide baru, tidak pernah mendapatkan kembali dimensi aslinya.",
"Ia yang mengerjakan lebih dari apa yang dibayar pada suatu saat akan dibayar lebih dari apa yang ia kerjakan.",
"Jangan biarkan opini orang lain menenggelamkan suara dari dalam dirimu.",
"Mulai setiap harimu dengan pikiran positif dan hati yang bersyukur."
"Jika kita terus melakukan apa yang kita lakukan, kita juga terus akan mendapatkan apa yang kita dapatkan." ,
"Jangan batasi tantanganmu, tapi tantang batasmu.",
"Pikirkan banyak hal, lakukan satu." ,
"Kualitas berarti melakukan sesuatu dengan benar saat tidak ada yang melihat." ,
"Prajurit yang sukses adalah orang biasa, dengan fokus seperti laser.",
"Bekerjalah lebih banyak dari orang lain karena usaha tidak pernah membohongi hasil.",
"Seseorang akan menjadi hebat jika dan hanya ia berusaha sesuai dengan apa yang ia minati.",
"Bekerja keras. Lakukan yang terbaik. Simpan kata-katamu. Jangan terlalu sombong. Percaya kepada Tuhan. Jangan takut dan jangan pernah lupakan teman.",
"Bekerjalah saat waktunya bekerja, bermainlah saat waktunya bermain. Hal tersebut adalah aturan dasar dari kedisiplinan diri yang represif.",
"Kecerdasan adalah kemampuan beradaptasi terhadap perubahan." ,
"Jangan menilai setiap hari berdasarkan panen yang kamu tuai, tetapi berdasarkan benih yang kamu tanam.",
 "Semua kemajuan terjadi di luar zona nyaman.",
"Satu-satunya cara untuk melakukan pekerjaan yang hebat adalah dengan mencintai apa yang kamu lakukan." ,
"Jadikan setiap hari mahakaryamu.",
"Kamu mungkin harus bertarung lebih dari sekali untuk memenangkannya.",
 "Jangan biarkan apa yang tidak dapat kamu lakukan mengganggu apa yang dapat kamu lakukan." ,
 "Kerjakan pekerjaan yang sulit terlebih dahulu. Pekerjaan mudah akan mengurus diri mereka sendiri." ,
 "Mengembangkan etos kerja yang baik adalah kuncinya. Terapkan dirimu pada apa pun yang kamu lakukan, apakah kamu seorang petugas kebersihan atau seseorang yang baru pertama kali bekerja pada saat musim panas, etos kerja itu akan tercermin dalam semua yang kamu lakukan dalam hidup.",
 "Kita harus percaya bahwa kita dikaruniai sesuatu dan hal ini harus dicapai.",
"Kualitas adalah pekerjaan pertama.",
"Kegagalan adalah bumbu yang memberi rasa keberhasilan." ,
"Selama niatnya baik, kesalahan bukan untuk memalukan, tetapi untuk dipelajari.",
 "Pekerjaan besar biasanya diberikan kepada orang-orang yang membuktikan kemampuan mereka melebihi pekerjaan kecil.",
"Bekerja keras, bersikap baik, dan hal-hal menakjubkan akan terjadi.",
"Jangan pernah menyerah pada mimpi hanya karena waktu yang dibutuhkan untuk mencapainya. Bagaimanapun waktu akan berlalu.",
  ]


           
@bot.on_message(filters.command("start"))
async def start_message(client: Client, message: Message):
    await message.reply(f"Selamat bermain dan selamat bersenang - senang\n\nJangan lupa subs @{CHANNEL} dan contact @{OWNER} untuk info lainnya.\n\nBy : @gendhis_gemooy")
    
@bot.on_message(filters.command("help"))
async def help_message(client: Client, message: Message):
    await message.reply("/bucin - bucin dulu\n/renungan - renungan dulu\n/donasi - donasi ke owner bot\n/request - request kamu")

    
@bot.on_message(filters.command("bucin"))
async def bucin(client: Client, message: Message):
    await message.reply(choice(BUCIN))
    
  
@bot.on_message(filters.command("motivasi"))
async def motivasi(client: Client, message: Message):
    await message.reply(choice(MOTIVASI))

@bot.on_message(filters.command("donasi"))
async def donasi(client: Client, message: Message):
    await message.reply(f"Yuk Support Bot Gendhis Dengan Cara Donasi\nDukung Gendhis Bot agar dapat selalu berkembang dan dapat membayar biaya server bot dengan cara donasi. sedikit bantuan dari anda sangat berharga.\ncontact : @{OWNER}")
    
@bot.on_message(filters.command("request"))
async def request(client: Client, message: Message):
    if len(message.command) < 2:
         return await message.reply("contoh = `/request Cukup China aja yang jauh, cinta kita jangan`")
    mmk = message.command[1:]
    kontol = " ".join(mmk)
    await bot.send_message(LOG_CHAT, f"{message.from_user.mention}\nPesan: `{kontol}`")
    await message.reply("Terimakasih telah berkontribusi untuk kami")
    
@bot.on_message(filters.command("repo"))
async def repos(client: Client, message: Message):
    await message.reply("[SPILL AND DRINK](https://github.com/)\nCek aja udah ada di Github")

bot.run()
